CREATE TABLE seguimiento_envios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_seguimiento VARCHAR2(255) NOT NULL UNIQUE,
    estado VARCHAR2(255) NOT NULL,
    ubicacion_actual VARCHAR2(255) NOT NULL,
    destinatario VARCHAR2(255) NOT NULL,
    detalle_producto VARCHAR2(255) NOT NULL
);
